<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\active_queries\SupportingDocumentQuery;

/**
 * This is the base-model class for table "supporting_document".
 *
 * @property integer $id
 * @property string $file_name
 * @property string $file_extension
 * @property string $file_path
 * @property integer $version
 * @property integer $is_active
 * @property string $environment
 * @property integer $created_at
 * @property integer $updated_at
 */
abstract class SupportingDocument extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'supporting_document';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['is_active'], 'default', 'value' => 1],
            [['environment'], 'default', 'value' => 'development'],
            [['file_name', 'file_extension', 'file_path'], 'required'],
            [['file_path'], 'string'],
            [['version', 'is_active'], 'integer'],
            [['file_name', 'file_extension', 'environment'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('models', 'ID'),
            'file_name' => Yii::t('models', 'File Name'),
            'file_extension' => Yii::t('models', 'File Extension'),
            'file_path' => Yii::t('models', 'File Path'),
            'version' => Yii::t('models', 'Version'),
            'is_active' => Yii::t('models', 'Is Active'),
            'environment' => Yii::t('models', 'Environment'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
        ]);
    }

    /**
     * @inheritdoc
     * @return SupportingDocumentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SupportingDocumentQuery(static::class);
    }
}
